### ISSUE TITLE
Changing display turn off timer?

### ISSUE THREAD

**Issue by Stanzilla** [lkorth/screen-notifications#49]
Since this is kinda the only app that I'm using that is somehow related to this, I have to ask if Screen notifications could, by any chance, be the cause of my display sleep timer resetting to 2min. It only happens sometimes and I can't really reproduce it by changing stuff in SN, but yeah. I just figured I'd ask here if anything in your code _could_ maybe cause that.

**Comment by lkorth** [comment]
It used to change the timer, but that was several versions ago.
